# Generated by Django 3.2.7 on 2022-08-18 04:48

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('front', '0089_questitemlocations_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='questitemlocations',
            name='icon',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_icon', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
