# Generated by Django 3.2.7 on 2022-08-18 05:17

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0091_auto_20220818_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questitemlocations',
            name='geom',
            field=djgeojson.fields.PointField(blank=True, null=True),
        ),
    ]
