# Generated by Django 3.2.7 on 2022-08-18 05:50

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0094_alter_questitemlocations_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questitemlocations',
            name='geom',
            field=djgeojson.fields.MultiPointField(blank=True, null=True),
        ),
    ]
