# Generated by Django 3.2.7 on 2022-08-18 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0095_alter_questitemlocations_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='questitemlocations',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.location'),
        ),
        migrations.AlterField(
            model_name='questitemlocations',
            name='flag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.blueflags'),
        ),
    ]
