# Generated by Django 3.2.7 on 2022-08-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0096_auto_20220818_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='questitemlocations',
            name='itemname',
            field=models.CharField(default='Snap Hook', max_length=64),
            preserve_default=False,
        ),
    ]
