# Generated by Django 3.2.7 on 2022-08-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0099_cosmetics_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cosmetics',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='cosmetics',
            name='name',
            field=models.CharField(default='test', max_length=64),
            preserve_default=False,
        ),
    ]
