# Generated by Django 3.2.7 on 2022-08-20 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0100_auto_20220820_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosmetics',
            name='adventure',
        ),
        migrations.RemoveField(
            model_name='cosmetics',
            name='crafting',
        ),
        migrations.RemoveField(
            model_name='cosmetics',
            name='gathering',
        ),
        migrations.RemoveField(
            model_name='cosmetics',
            name='guild',
        ),
        migrations.RemoveField(
            model_name='cosmetics',
            name='land',
        ),
        migrations.RemoveField(
            model_name='cosmetics',
            name='reputation',
        ),
        migrations.RemoveField(
            model_name='cosmetics',
            name='reputation_guild_value',
        ),
        migrations.RemoveField(
            model_name='cosmetics',
            name='weapon',
        ),
    ]
