# Generated by Django 3.2.7 on 2022-08-21 01:35

import auto_prefetch
from django.db import migrations
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0104_auto_20220821_0111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blueflagsreward',
            options={'base_manager_name': 'prefetch_manager'},
        ),
        migrations.AlterModelOptions(
            name='blueflagsstep',
            options={'base_manager_name': 'prefetch_manager'},
        ),
        migrations.AlterModelOptions(
            name='bossweakness',
            options={'base_manager_name': 'prefetch_manager'},
        ),
        migrations.AlterModelOptions(
            name='companionskill',
            options={'base_manager_name': 'prefetch_manager'},
        ),
        migrations.AlterModelOptions(
            name='elixir',
            options={'base_manager_name': 'prefetch_manager'},
        ),
        migrations.AlterModelOptions(
            name='gatheringpoint',
            options={'base_manager_name': 'prefetch_manager'},
        ),
        migrations.AlterModelOptions(
            name='monsterweakness',
            options={'base_manager_name': 'prefetch_manager'},
        ),
        migrations.AlterModelOptions(
            name='somberseason',
            options={'base_manager_name': 'prefetch_manager'},
        ),
        migrations.AlterModelManagers(
            name='adventure',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='blueflags',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='blueflagsreward',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='blueflagsstep',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='boss',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='bossweakness',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='companion',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='companionskill',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='component',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='componenttype',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='cosmetics',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='crafting',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='daytime',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='elixir',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='equipmentslot',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='gathering',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='gatheringpoint',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='guide',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='guild',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='land',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='location',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='magicschool',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='material',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='materialtype',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='monster',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='monsterweakness',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='npc',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='plant',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='questitemlocations',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='recipe',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='region',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='reputation',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='somberseason',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='talent',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='training',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='weapon',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='blueflagsreward',
            name='component',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.component'),
        ),
        migrations.AlterField(
            model_name='blueflagsreward',
            name='flag',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.blueflags'),
        ),
        migrations.AlterField(
            model_name='blueflagsreward',
            name='material',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.material'),
        ),
        migrations.AlterField(
            model_name='blueflagsreward',
            name='plant',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.plant'),
        ),
        migrations.AlterField(
            model_name='blueflagsstep',
            name='adventure',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.adventure'),
        ),
        migrations.AlterField(
            model_name='blueflagsstep',
            name='flag',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.blueflags'),
        ),
        migrations.AlterField(
            model_name='blueflagsstep',
            name='gathering',
            field=auto_prefetch.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.gathering'),
        ),
        migrations.AlterField(
            model_name='blueflagsstep',
            name='monster1',
            field=auto_prefetch.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monster1', to='front.monster'),
        ),
        migrations.AlterField(
            model_name='blueflagsstep',
            name='monster2',
            field=auto_prefetch.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monster2', to='front.monster'),
        ),
        migrations.AlterField(
            model_name='blueflagsstep',
            name='monster3',
            field=auto_prefetch.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monster3', to='front.monster'),
        ),
        migrations.AlterField(
            model_name='blueflagsstep',
            name='monster4',
            field=auto_prefetch.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monster4', to='front.monster'),
        ),
        migrations.AlterField(
            model_name='blueflagsstep',
            name='monster5',
            field=auto_prefetch.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monster5', to='front.monster'),
        ),
        migrations.AlterField(
            model_name='blueflagsstep',
            name='weapon',
            field=auto_prefetch.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.weapon'),
        ),
        migrations.AlterField(
            model_name='book',
            name='adventure',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.adventure'),
        ),
        migrations.AlterField(
            model_name='book',
            name='blueflag',
            field=auto_prefetch.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.blueflags'),
        ),
        migrations.AlterField(
            model_name='book',
            name='crafting',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.crafting'),
        ),
        migrations.AlterField(
            model_name='book',
            name='gathering',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.gathering'),
        ),
        migrations.AlterField(
            model_name='book',
            name='guild',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.guild'),
        ),
        migrations.AlterField(
            model_name='book',
            name='land',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.land'),
        ),
        migrations.AlterField(
            model_name='book',
            name='location',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.location'),
        ),
        migrations.AlterField(
            model_name='book',
            name='npc',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.npc'),
        ),
        migrations.AlterField(
            model_name='book',
            name='reputation',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.reputation'),
        ),
        migrations.AlterField(
            model_name='book',
            name='weapon',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.weapon'),
        ),
        migrations.AlterField(
            model_name='boss',
            name='substance',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.component'),
        ),
        migrations.AlterField(
            model_name='bossweakness',
            name='boss',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.boss'),
        ),
        migrations.AlterField(
            model_name='bossweakness',
            name='magic_school',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.magicschool'),
        ),
        migrations.AlterField(
            model_name='companion',
            name='location',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.location'),
        ),
        migrations.AlterField(
            model_name='companion',
            name='weapon',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.weapon'),
        ),
        migrations.AlterField(
            model_name='companionskill',
            name='adventure',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.adventure'),
        ),
        migrations.AlterField(
            model_name='companionskill',
            name='companion',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.companion'),
        ),
        migrations.AlterField(
            model_name='companionskill',
            name='crafting',
            field=auto_prefetch.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.crafting'),
        ),
        migrations.AlterField(
            model_name='companionskill',
            name='gathering',
            field=auto_prefetch.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.gathering'),
        ),
        migrations.AlterField(
            model_name='companionskill',
            name='land',
            field=auto_prefetch.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.land'),
        ),
        migrations.AlterField(
            model_name='component',
            name='component_type',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.componenttype'),
        ),
        migrations.AlterField(
            model_name='cosmetics',
            name='blueflag',
            field=auto_prefetch.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.blueflags'),
        ),
        migrations.AlterField(
            model_name='cosmetics',
            name='location',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.location'),
        ),
        migrations.AlterField(
            model_name='cosmetics',
            name='npc',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.npc'),
        ),
        migrations.AlterField(
            model_name='gatheringpoint',
            name='material',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.material'),
        ),
        migrations.AlterField(
            model_name='gatheringpoint',
            name='plant',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.plant'),
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.region'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.materialtype'),
        ),
        migrations.AlterField(
            model_name='materialtype',
            name='gathering',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.gathering'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='region',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.region'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='substance',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.component'),
        ),
        migrations.AlterField(
            model_name='monsterweakness',
            name='magic_school',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.magicschool'),
        ),
        migrations.AlterField(
            model_name='monsterweakness',
            name='monster',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.monster'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='daytime',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.daytime'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='location',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.location'),
        ),
        migrations.AlterField(
            model_name='questitemlocations',
            name='flag',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.blueflags'),
        ),
        migrations.AlterField(
            model_name='questitemlocations',
            name='location',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.location'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='blueflag',
            field=auto_prefetch.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.blueflags'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='equipment_slot',
            field=auto_prefetch.ForeignKey(blank=True, help_text='If not a building', null=True, on_delete=django.db.models.deletion.CASCADE, to='front.equipmentslot'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='guild',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.guild'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='location',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.location'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='npc',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.npc'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='reputation',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.reputation'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='weapon',
            field=auto_prefetch.ForeignKey(blank=True, help_text='If equipment_slot is weapon', null=True, on_delete=django.db.models.deletion.CASCADE, to='front.weapon'),
        ),
        migrations.AlterField(
            model_name='region',
            name='land',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.land'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='guild',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.guild'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='location',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.location'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='npc',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.npc'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='reputation',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.reputation'),
        ),
        migrations.AlterField(
            model_name='training',
            name='adventure',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.adventure'),
        ),
        migrations.AlterField(
            model_name='training',
            name='daytime',
            field=auto_prefetch.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.daytime'),
        ),
        migrations.AlterField(
            model_name='training',
            name='location',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.location'),
        ),
    ]
