# Generated by Django 3.2.7 on 2022-08-21 02:54

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0105_auto_20220821_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueflagsreward',
            name='flag',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BlueFlags', to='front.blueflags'),
        ),
    ]
