# Generated by Django 3.2.7 on 2022-08-21 03:01

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0106_alter_blueflagsreward_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueflagsreward',
            name='flag',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.blueflags'),
        ),
    ]
