# Generated by Django 3.2.7 on 2022-08-23 05:29

import auto_prefetch
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0107_alter_blueflagsreward_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boss',
            name='geom',
        ),
        migrations.AddField(
            model_name='boss',
            name='location',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.location'),
        ),
        migrations.AddField(
            model_name='location',
            name='is_boss',
            field=models.BooleanField(default=False),
        ),
    ]
