# Generated by Django 3.2.7 on 2022-08-23 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0109_rename_location_boss_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boss',
            name='geom',
        ),
    ]
