# Generated by Django 3.2.7 on 2022-08-23 05:42

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0110_remove_boss_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='boss',
            name='locations',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.location'),
        ),
    ]
