# Generated by Django 3.2.7 on 2022-08-23 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0111_boss_locations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boss',
            old_name='locations',
            new_name='location',
        ),
    ]
