# Generated by Django 3.2.7 on 2022-08-23 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0112_rename_locations_boss_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='is_boss',
        ),
    ]
