# Generated by Django 3.2.7 on 2023-01-22 06:30

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0114_auto_20220824_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='land',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.land'),
        ),
        migrations.AlterField(
            model_name='training',
            name='adventure',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.adventure'),
        ),
    ]
